// Copyright 2017-2021 @dust-defi/x-bundle authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@dust-defi/x-bundle', version: '7.8.2' };
