// Copyright 2017-2021 @reef-defi/util authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@dust-defi/util', version: '7.8.2' };
