// Copyright 2017-2021 @reef-defi/hw-ledger authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@dust-defi/hw-ledger', version: '7.8.2' };
