// Copyright 2017-2021 @reef-defi/x-fetch authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @reef-defi/dev, do not edit

export const packageInfo = { name: '@reef-defi/x-fetch', version: '7.8.2' };
