// Copyright 2017-2021 @dust-defi/x-fetch authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@dust-defi/x-fetch', version: '7.8.2' };
